version: '3.0'

expectations:
  population_size: 3000

actions:

  generate_study_population:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition
        --index-date-range "2020-01-01 to 2020-03-01 by month"
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  generate_ethnicity_cohort:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_ethnicity
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv.gz

  join_cohorts:
    run: >
      cohort-joiner:v0.0.44
        --lhs output/input_20*.csv.gz
        --rhs output/input_ethnicity.csv.gz
        --output-dir output/joined
    needs: [generate_study_population, generate_ethnicity_cohort]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_*.csv.gz

## generate Structured Medication Review Measures and plots

  generate_measures_smr:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition 
       --output-dir=output/joined
     needs: [join_cohorts]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_smr_*_rate.csv
  
## generate Medication Review measures
  generate_study_population_mr:
      run: >
        cohortextractor:latest generate_cohort
          --study-definition study_definition_mr
          --index-date-range "2020-01-01 to 2020-03-01 by month"
          --output-format='csv.gz'
      outputs:
        highly_sensitive:
          cohort: output/input_mr*.csv.gz

  join_cohorts_mr:
    run: >
      cohort-joiner:v0.0.44
        --lhs output/input_mr*.csv.gz
        --rhs output/input_ethnicity.csv.gz
        --output-dir output/joined
    needs: [generate_study_population_mr, generate_ethnicity_cohort]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_mr*.csv.gz
 
  generate_measures_mr:
    run: >
      cohortextractor:latest generate_measures 
        --study-definition study_definition_mr 
        --output-dir=output/joined
    needs: [join_cohorts_mr]
    outputs:
      moderately_sensitive:
        measure_csv: output/joined/measure_mr_*_rate.csv
 
  smr_plots:
    run: python:latest python analysis/plots.py
    needs: [generate_measures_smr, generate_measures_mr]
    outputs:
      moderately_sensitive:
        cohort: output/figures/*_*_rate.jpeg