version: '3.0'

expectations:
  population_size: 3000

actions:

  generate_study_population:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition
        --index-date-range "2019-04-01 to 2019-12-01 by month"
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input_2019*.csv.gz

  generate_study_population_range2:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition
        --index-date-range "2020-01-01 to 2020-12-01 by month"
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input_2020*.csv.gz

  generate_study_population_range3:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition
        --index-date-range "2021-01-01 to 2021-12-01 by month"
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input_2021*.csv.gz

  generate_study_population_range4:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition
        --index-date-range "2022-01-01 to 2022-03-01 by month"
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input_2022*.csv.gz

  generate_study_population_allmedrev:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_allmedrev
        --index-date-range "2019-04-01 to 2019-12-01 by month"
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input_allmedrev_2019*.csv.gz

  generate_study_population_allmedrev_range2:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_allmedrev
        --index-date-range "2020-01-01 to 2020-12-01 by month"
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort2: output/input_allmedrev_2020*.csv.gz

  generate_study_population_allmedrev_range3:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_allmedrev
        --index-date-range "2021-01-01 to 2021-12-01 by month"
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort3: output/input_allmedrev_2021*.csv.gz

  generate_study_population_allmedrev_range4:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_allmedrev
        --index-date-range "2022-01-01 to 2022-03-01 by month"
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort3: output/input_allmedrev_2022*.csv.gz

  generate_ethnicity_cohort:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_ethnicity
        --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv.gz

  join_cohorts:
    run: >
      cohort-joiner:v0.0.44
        --lhs output/input_20*.csv.gz
        --rhs output/input_ethnicity.csv.gz
        --output-dir output/joined
    needs: [generate_study_population, generate_study_population_range2, generate_study_population_range3, generate_study_population_range4, generate_ethnicity_cohort]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_20*.csv.gz

  join_cohorts_allmedrev:
    run: >
      cohort-joiner:v0.0.44
        --lhs output/input_allmedrev*.csv.gz
        --rhs output/input_ethnicity.csv.gz
        --output-dir output/joined
    needs: [generate_study_population_allmedrev, generate_study_population_allmedrev_range2, generate_study_population_allmedrev_range3, generate_study_population_allmedrev_range4, generate_ethnicity_cohort]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_allmedrev_*.csv.gz

## generate Structured Medication Review Measures and plots

  generate_measures_mr_smr:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition
       --output-dir=output/joined
     needs: [join_cohorts]
     outputs:
       moderately_sensitive:
         mr_measure_csv: output/joined/measure_mr_*_rate.csv
         mr12m_measure_csv: output/joined/measure_mr12m_*_rate.csv
         smr_measure_csv: output/joined/measure_smr_*_rate.csv
         smr12m_measure_csv: output/joined/measure_smr12m_*_rate.csv
         smr_measure_asgrouped_csv: output/joined/measure_smr_*_rate_agesexstandardgrouped.csv
         smr12m_measure_asgrouped_csv: output/joined/measure_smr12m_*_rate_agesexstandardgrouped.csv

  generate_measures_all_reviews:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_allmedrev
       --output-dir=output/joined
     needs: [join_cohorts_allmedrev]
     outputs:
       moderately_sensitive:
         allmedrev_measure_csv: output/joined/measure_allmedrv_*_rate.csv
         allmedrev12m_measure_csv: output/joined/measure_allmedrv12m_*_rate.csv
         allmedrev_measure_asgrouped_csv: output/joined/measure_allmedrv_*_rate_agesexstandardgrouped.csv                   
         allmedrev12m_measure_asgrouped_csv: output/joined/measure_allmedrv12m_*_rate_agesexstandardgrouped.csv

  generate_deciles_charts:
    run: >
      deciles-charts:v0.0.33
        --input-files output/joined/measure_*_practice_rate.csv
        --output-dir output/joined
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [generate_measures_mr_smr, generate_measures_all_reviews]
    outputs:
      moderately_sensitive:
        deciles_charts: output/joined/deciles_*_*.*

  redact_and_round:
    run: python:latest python analysis/redact_and_round.py
    needs: [generate_measures_mr_smr, generate_codeuse_output, generate_allmedrev_codeuse_output, generate_measures_all_reviews]
    outputs:
      moderately_sensitive:
        cohort: output/redacted/redacted_measure_*.csv
        cohort_codeuse: output/redacted/redacted_totalcodeuse*.csv

  redact_and_round_standardised:
    run: python:latest python analysis/standardised_redact_and_round.py
    needs: [agesexstandardise_demographics]
    outputs:
      moderately_sensitive:
        cohort: output/redacted-standardised/redacted_standardised_*.csv

  generate_plots:
    run: python:latest python analysis/plots.py
    needs: [redact_and_round, generate_deciles_charts]
    outputs:
      moderately_sensitive:
        percent_cohort: output/figures/*_*_rate_percentage.jpeg
        perthousand_cohort: output/figures/*_*_rate_perthousand.jpeg 

  generate_standardised_plots:
    run: python:latest python analysis/standardised-plots.py
    needs: [redact_and_round_standardised]
    outputs:
      moderately_sensitive:
        standard_figures: output/figures-standardised/*_*_standardised.jpeg

  generate_table_1:
    run: python:latest python analysis/table_1.py --study_def_paths="output/joined/input_allmedrev_*.csv.gz" --demographics="age_band,sex,region,imdQ5,ethnicity,learning_disability,care_home_type,addictivemeds_last12m,dmards_last12m,teratogenicmeds_last12m,highriskmeds_last12m" --outcome "had_anymedrev"
    needs: [join_cohorts_allmedrev]
    outputs:
      moderately_sensitive:
        counts: output/table_1.csv
        had_outcome: output/table_1_had_outcome.csv

  generate_codeuse_output:
    run: python:latest python analysis/code_use_summary.py --study_def_paths="output/joined/input_20*.csv.gz" --codelistfile="user-chriswood-medication-review.csv" --outputfile="codeuse"
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        code_counts: output/codeuse.csv
        total_code_counts: output/totalcodeuse.csv

  generate_allmedrev_codeuse_output:
    run: python:latest python analysis/code_use_summary.py --study_def_paths="output/joined/input_allmedrev_*.csv.gz" --codelistfile="user-chriswood-all-medication-reviews.csv" --outputfile="codeuse_allmedrev"
    needs: [join_cohorts_allmedrev]
    outputs:
      moderately_sensitive:
        code_counts: output/codeuse_allmedrev.csv
        total_code_counts: output/totalcodeuse_allmedrev.csv

  correct_age_bands:
    run: python:latest python analysis/correct_age_groups.py
    needs: [generate_measures_mr_smr, generate_measures_all_reviews]
    outputs:
      moderately_sensitive:
        prestandarised_tables: output/correctedagegroupsmeasures/measure_allmedrv_*_rate_agesexstandardgrouped_corrected.csv
        prestandarised_tables12m: output/correctedagegroupsmeasures/measure_allmedrv12m_*_rate_agesexstandardgrouped_corrected.csv
        prestandarised_smr_tables: output/correctedagegroupsmeasures/measure_smr_*_rate_agesexstandardgrouped_corrected.csv
        prestandarised_smr_tables12m: output/correctedagegroupsmeasures/measure_smr12m_*_rate_agesexstandardgrouped_corrected.csv

  agesexstandardise_demographics:
    run: python:latest python analysis/rate_calculations_demographics.py
    needs: [correct_age_bands]
    outputs:
      moderately_sensitive:
        standarised_tables: output/correctedagegroupsmeasures/allmedrv_*_standardised.csv
        standarised_tables12m: output/correctedagegroupsmeasures/allmedrv12m_*_standardised.csv
        standarised_smr_tables: output/correctedagegroupsmeasures/smr_*_standardised.csv
        standarised_smr_tables12m: output/correctedagegroupsmeasures/smr12m_*_standardised.csv

  run_tests:
    run: python:latest python -m pytest --junit-xml=output/pytest.xml --verbose
    outputs:
      moderately_sensitive:
        log: output/pytest.xml

  ####
  # REPORT ACTIONS
  ####
  generate_study_population_report_ethnicity:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_ethnicity_report --output-dir output/report --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/report/input_ethnicity_report.csv.gz


  generate_study_population_report:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_report 
      --param codelist_1_path="codelists/opensafely-medication-reviews-all-types.csv"
      --param codelist_1_column="code"
      --param codelist_1_system="snomed"
      --param codelist_1_type="medication"
      --param codelist_2_path="codelists/opensafely-dmards.csv"
      --param codelist_2_column="snomed_id"
      --param codelist_2_system="snomed"
      --param codelist_2_type="medication"
      --param codelist_1_frequency="monthly"
      --param codelist_2_comparison_date="event_1_date"
      --param codelist_2_period_start="- 365"
      --param codelist_2_period_end="+ 0"
      --param operator="AND"
      --param population="registered_adults"
      --param breakdowns="sex,age_band,imd,region"
      --index-date-range "2019-01-01 to 2022-11-01 by month" 
      --output-dir=output/report
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/report/input_*.csv.gz

  join_cohorts_report:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/report/input_report_20*.csv.gz
        --rhs output/report/input_ethnicity_report.csv.gz
        --output-dir output/report/joined
    needs: [generate_study_population_report, generate_study_population_report_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/report/joined/input_report_20*.csv.gz
  
  generate_measures_report:
    run: >
      python:latest python analysis/report/measures_report.py
      --breakdowns="sex,age_band,imd,region,ethnicity" 
      --input_dir="output/report/joined" 
      --measure="med_review"

    needs: [join_cohorts_report]
    outputs:
      moderately_sensitive:
        measure: output/report/joined/measure*rate.csv
        decile_measure: output/report/joined/measure*rate_deciles.csv

  top_5_table_report:
    run: >
      python:latest python analysis/report/top_5_report.py
      --codelist-1-path="codelists/opensafely-medication-reviews-all-types.csv"
      --codelist-2-path="codelists/opensafely-dmards.csv"
    needs: [generate_measures_report]
    outputs:
      moderately_sensitive:
        tables: output/report/joined/top_5*.csv

  deciles_chart_report:
    run: >
      deciles-charts:v0.0.33
        --input-files output/report/joined/measure_practice_rate_deciles.csv
        --output-dir output/report/joined
    config:
      show_outer_percentiles: true
      tables:
        output: true
      charts:
        output: true
    needs: [generate_measures_report]
    outputs:
      moderately_sensitive:
        deciles_charts: output/report/joined/deciles_*.*
  
  plot_measure_report:
    run: >
      python:latest python analysis/report/plot_measures_report.py --breakdowns="sex,imd,region,age_band,ethnicity"
    needs: [generate_measures_report]
    outputs:
      moderately_sensitive:
        measure: output/report/plot_measure*.jpeg
        
  event_counts_report:
    run: >
      python:latest python analysis/report/event_counts.py --input_dir="output/report/joined" --output_dir="output/report"
    needs: [join_cohorts_report]
    outputs:
      moderately_sensitive:
        measure: output/report/event_counts.json

  create_notebook:
    run: >
      python:latest python analysis/report/create_notebook.py
      --codelist-1-description="Codelist 1 description"
      --codelist-2-description="Codelist 2 description"
      --codelist-1-link="https://codelists.opensafely.org/codelist/user/chriswood/all-medication-reviews/2021-04-01/"
      --codelist-2-link="https://codelists.opensafely.org/codelist/opensafely/dmards/2021-04-01/"
      --report-title="Medication Review Report"
      --measure-description="Medication Review"
      --population="adults"
      --demographics="sex"
      --demographics="age_band"
    outputs:
      moderately_sensitive:
        notebook: output/report/report.ipynb

  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/output/report/report.ipynb --execute --to html --output-dir=/workspace/output/report --ExecutePreprocessor.timeout=86400 --no-input
    needs: [create_notebook, event_counts_report, deciles_chart_report, top_5_table_report, plot_measure_report]
    outputs:
      moderately_sensitive:
        notebook: output/report/report.html

  
  generate_study_population_report_ever:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_report_windows 
      --param codelist_1_path="codelists/opensafely-medication-reviews-all-types.csv"
      --param codelist_1_column="code"
      --param codelist_1_system="snomed"
      --param codelist_1_type="medication"
      --param population="registered_adults"
      --index-date-range "2019-01-01 to 2020-01-01 by month" 
      --output-dir=output/report
      --output-format=csv.gz
      --param time_window="ever"
    outputs:
      highly_sensitive:
        cohort: output/report/input_report_windows*.csv.gz

  generate_study_population_report_five_years:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_report_windows 
      --param codelist_1_path="codelists/opensafely-medication-reviews-all-types.csv"
      --param codelist_1_column="code"
      --param codelist_1_system="snomed"
      --param codelist_1_type="medication"
      --param population="registered_adults"
      --index-date-range "2019-01-01 to 2020-01-01 by month" 
      --output-dir=output/report
      --output-format=csv.gz
      --param time_window="5 years"
    outputs:
      highly_sensitive:
        cohort: output/report/input_report_window*.csv.gz

  generate_study_population_report_month:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_report_windows 
      --param codelist_1_path="codelists/opensafely-medication-reviews-all-types.csv"
      --param codelist_1_column="code"
      --param codelist_1_system="snomed"
      --param codelist_1_type="medication"
      --param population="registered_adults"
      --index-date-range "2019-01-01 to 2020-01-01 by month" 
      --output-dir=output/report
      --output-format=csv.gz
      --param time_window="1 month"
    outputs:
      highly_sensitive:
        cohort: output/report/input_report_windo*.csv.gz
  
  generate_study_population_report_2_year:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_report_windows 
      --param codelist_1_path="codelists/opensafely-medication-reviews-all-types.csv"
      --param codelist_1_column="code"
      --param codelist_1_system="snomed"
      --param codelist_1_type="medication"
      --param population="registered_adults"
      --index-date-range "2019-01-01 to 2020-01-01 by month" 
      --output-dir=output/report
      --output-format=csv.gz
      --param time_window="2 years"
    outputs:
      highly_sensitive:
        cohort: output/report/input_report_wind*.csv.gz
