version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition
        --index-date-range "2020-01-01 to 2020-02-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_ethnicity_cohort:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_ethnicity
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv
